[package]
name = "pomocli"
version = "0.1.0"
edition = "2024"

[dependencies]
figlet-rs = "0.1.0"
terminal_size = "0.2"
notify-rust = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
json_comments = "0.2"
dirs = "5.0"